<a href="https://colab.research.google.com/github/reddy996654/MACHINE-LEARNING/blob/main/HMM_Sequential_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install hmmlearn

import numpy as np
from hmmlearn import hmm

# 1. Create Sequential Data
# Let's create a synthetic sequence of observations.
# Imagine 2 hidden states (e.g., "Sunny", "Rainy")
# and 3 observable activities (0="Walk", 1="Shop", 2="Clean").
# We'll create a single long sequence of observations.
X_sequence = np.array([
    0, 1, 2, 0, 0, 1, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 1, 2, 1,
    0, 0, 0, 1, 2, 1, 1, 0, 2, 1, 2, 0, 1, 0, 0, 2, 1, 2, 0, 0
]).reshape(-1, 1) # Needs to be a 2D array

# 2. Implement HMM
# We'll use a MultinomialHMM since our observations are discrete (0, 1, 2).
# We assume 2 hidden states (n_components=2).
model = hmm.MultinomialHMM(n_components=2, random_state=42, n_iter=100)
model.fit(X_sequence)

# 3. Predict Hidden States
hidden_states = model.predict(X_sequence)

print("Generated Observation Sequence (first 20):")
print(X_sequence.flatten()[:20])

print("\nPredicted Hidden States (first 20):")
print(hidden_states[:20])

# 4. Display Numerical Outputs (The "Learned" Model)
print("\n--- Model Parameters ---")

# Transition Matrix (Probability of going from State i to State j)
print("\nTransition Matrix (State-to-State):")
print(model.transmat_)

# Emission Matrix (Probability of observing Symbol k while in State i)
print("\nEmission Probabilities (State-to-Observation):")
print(model.emissionprob_)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 2.4 MB/s eta 0:00:00


https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


Generated Observation Sequence (first 20):
[0 1 2 0 0 1 2 1 0 0 1 2 2 1 0 0 1 1 2 1]

Predicted Hidden States (first 20):
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

--- Model Parameters ---

Transition Matrix (State-to-State):
[[0.87827377 0.12172623]
 [0.99887354 0.00112646]]

Emission Probabilities (State-to-Observation):
[[1.]
 [1.]]
